/**
 * ASSETS CONFIGURATION
 * 
 * Centralized location for all external resource paths.
 * This makes it easy to swap targets or videos without touching engine logic.
 */
export const ASSETS = {
    targets: {
        // Path to the .mind file generated by MindAR compiler
        postcard: '/targets/tiffin.mind'
    },
    videos: {
        // Path to the video file to be displayed on the target
        promo: '/videos/tiffin.mp4'
    },
    images: {
        // Fallback or preview images
        postcard: '/images/tiffin.jpg'
    }
};
